FROM docker.io/library/golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o master cmd/master/main.go

FROM docker.io/library/alpine:latest
WORKDIR /app
COPY --from=builder /app/master .
# config will be mounted
EXPOSE 8080
ENTRYPOINT ["./master"]
