FROM docker.io/library/golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o satellite cmd/satellite/main.go

FROM docker.io/library/alpine:latest
WORKDIR /app
COPY --from=builder /app/satellite .
ENTRYPOINT ["./satellite"]
